//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int IdNotificacion { get; set; }
        public int IdPedido { get; set; }
        public int IdTipoNotificacion { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
