//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.ActualizacionPedidos = new HashSet<ActualizacionPedidos>();
            this.DetallePedido = new HashSet<DetallePedido>();
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int IdPedido { get; set; }
        public int IdUsuario { get; set; }
        public byte IdSucursal { get; set; }
        public Nullable<byte> IdTipoPago { get; set; }
        public int IdDireccion { get; set; }
        public byte IdEstadoPedido { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActualizacionPedidos> ActualizacionPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
